#ifndef CALCULATORZ_FRONTEND_GLOBAL_H
#define CALCULATORZ_FRONTEND_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CALCULATORZ_FRONTEND_LIBRARY)
#define CALCULATORZ_FRONTEND_EXPORT Q_DECL_EXPORT
#else
#define CALCULATORZ_FRONTEND_EXPORT Q_DECL_IMPORT
#endif

#endif // CALCULATORZ_FRONTEND_GLOBAL_H
